// services/publicContent.js — Weekly public content: sample brief + SEO market roundups
// Generated by the Sunday cron after subscriber sends. Zero marginal cost beyond one
// LLM call per page; data comes from the same fetch pipeline (cached snapshots help).

import { fetchSoldSales, computeTrend } from './cardhedge.js';
import { generateCommentary } from './llm.js';
import { query } from '../db/index.js';

const SAMPLE_SUBSCRIBER = {
  id: 'sample',
  first_name: null,
  niche: 'Sports Cards & Pokémon',
  watchlist: [
    { label: 'PSA 10 1999 Charizard Base Set Holo', keywords: 'charizard base set holo PSA 10' },
    { label: '2018 Luka Doncic Prizm PSA 10', keywords: 'luka doncic prizm 2018 PSA 10' },
    { label: '1986 Fleer Michael Jordan PSA 8', keywords: '1986 fleer michael jordan PSA 8' },
    { label: '2000 Tom Brady Bowman Chrome PSA 9', keywords: 'tom brady bowman chrome 2000 PSA 9' },
  ],
};

const MARKET_NICHES = [
  { slug: 'pokemon', name: 'Pokémon Cards', items: [
    { label: 'PSA 10 1999 Charizard Base Set Holo', keywords: 'charizard base set holo PSA 10' },
    { label: 'PSA 10 Umbreon VMAX Alt Art', keywords: 'umbreon vmax alt art PSA 10' },
    { label: 'PSA 10 1999 Blastoise Base Set Holo', keywords: 'blastoise base set holo PSA 10' },
  ]},
  { slug: 'sports-cards', name: 'Sports Cards', items: [
    { label: '2018 Luka Doncic Prizm PSA 10', keywords: 'luka doncic prizm 2018 PSA 10' },
    { label: '2017 Patrick Mahomes Prizm PSA 10', keywords: 'patrick mahomes prizm 2017 PSA 10' },
    { label: '1986 Fleer Michael Jordan PSA 8', keywords: '1986 fleer michael jordan PSA 8' },
  ]},
];

/** Regenerate the public sample brief for this week. */
export async function generateSampleBrief(weekOf) {
  const itemResults = await fetchItems(SAMPLE_SUBSCRIBER.watchlist);
  const commentary = await generateCommentary(SAMPLE_SUBSCRIBER, itemResults).catch(() => null);
  const html = renderPublicBrief(itemResults, commentary, weekOf);

  await query(
    `INSERT INTO sample_briefs (week_of, html) VALUES ($1, $2)
     ON CONFLICT (week_of) DO UPDATE SET html=EXCLUDED.html, created_at=NOW()`,
    [weekOf, html]
  );
  console.log('[PublicContent] Sample brief generated');
  return html;
}

/** Regenerate SEO market pages for all configured niches. */
export async function generateMarketPages(weekOf) {
  for (const niche of MARKET_NICHES) {
    try {
      const itemResults = await fetchItems(niche.items);
      const commentary = await generateCommentary(
        { niche: niche.name, watchlist: niche.items }, itemResults
      ).catch(() => null);
      const html = renderMarketPage(niche, itemResults, commentary, weekOf);
      await query(
        `INSERT INTO market_pages (niche_slug, week_of, html) VALUES ($1, $2, $3)
         ON CONFLICT (niche_slug, week_of) DO UPDATE SET html=EXCLUDED.html, created_at=NOW()`,
        [niche.slug, weekOf, html]
      );
      console.log(`[PublicContent] Market page generated: /market/${niche.slug}`);
    } catch (err) {
      console.error(`[PublicContent] Market page failed (${niche.slug}):`, err.message);
    }
  }
}

/**
 * Regenerate the "Trending This Week" leaderboard — aggregates every item
 * across all configured niches, ranked by absolute % move. Zero new API
 * calls: reuses the same fetchItems() results the market pages already need,
 * so this is a same-cost byproduct of the existing weekly generation pass.
 */
export async function generateTrendingPage(weekOf) {
  const allRanked = [];

  for (const niche of MARKET_NICHES) {
    try {
      const itemResults = await fetchItems(niche.items);
      for (const item of itemResults) {
        if (item.trend.count > 0) {
          allRanked.push({ ...item, nicheName: niche.name, nicheSlug: niche.slug });
        }
      }
    } catch (err) {
      console.error(`[PublicContent] Trending fetch failed (${niche.slug}):`, err.message);
    }
  }

  // Rank by absolute % move (pctChange from computeTrend), biggest movers first
  allRanked.sort((a, b) => Math.abs(b.trend.pctChange || 0) - Math.abs(a.trend.pctChange || 0));

  const html = renderTrendingPage(allRanked.slice(0, 12), weekOf);

  await query(
    `INSERT INTO trending_pages (week_of, html) VALUES ($1, $2)
     ON CONFLICT (week_of) DO UPDATE SET html=EXCLUDED.html, created_at=NOW()`,
    [weekOf, html]
  );
  console.log('[PublicContent] Trending page generated');
  return html;
}

async function fetchItems(items) {
  const results = await Promise.allSettled(
    items.map(async (item) => {
      const sales = await fetchSoldSales(item.keywords, { limit: 20, daysBack: 7 }).catch(() => []);
      return { label: item.label, keywords: item.keywords, sales, trend: computeTrend(sales) };
    })
  );
  return results
    .filter(r => r.status === 'fulfilled')
    .map(r => r.value);
}

function itemTable(itemResults) {
  const trendIcon = { up: '📈', down: '📉', stable: '➡️' };
  return itemResults.map(item => `
    <tr>
      <td style="padding:16px 0;border-bottom:1px solid #eee">
        <h3 style="margin:0 0 6px;font-size:17px;color:#1a1a1a">${trendIcon[item.trend.trend] || '➡️'} ${esc(item.label)}</h3>
        <p style="margin:0;color:#666;font-size:14px">
          ${item.trend.count} sales · avg <strong>$${item.trend.avg}</strong> · range $${item.trend.min}–$${item.trend.max} · trend: <strong>${item.trend.trend}</strong>
        </p>
        ${item.sales.slice(0, 3).map(s => `<p style="margin:4px 0 0;color:#999;font-size:12px">${esc(s.title.slice(0, 60))} — <strong style="color:#444">$${s.price}</strong></p>`).join('')}
      </td>
    </tr>`).join('');
}

function renderPublicBrief(itemResults, commentary, weekOf) {
  const wLabel = label(weekOf);
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sample Brief — Week of ${wLabel} · CollectrBrief</title>
<meta name="description" content="A real example of the personalized weekly market brief CollectrBrief subscribers receive — live sold prices, trends, and AI market commentary."></head>
<body style="margin:0;padding:0;background:#f9f6f1;font-family:Georgia,serif">
<div style="max-width:620px;margin:0 auto;padding:32px 16px">
  <div style="text-align:center;margin-bottom:8px">
    <span style="font-size:26px;font-weight:700;color:#1a1a1a">CollectrBrief</span>
    <p style="color:#888;font-size:13px;margin:4px 0">SAMPLE BRIEF · Week of ${wLabel}</p>
    <p style="color:#b45309;background:#fef3c7;display:inline-block;padding:4px 12px;border-radius:999px;font-size:12px">This is a live example — subscribers get this for THEIR items</p>
  </div>
  <div style="background:#fff;border-radius:8px;padding:24px;margin:20px 0;border:1px solid #eee">
    <h2 style="margin:0 0 16px;font-size:16px;text-transform:uppercase;letter-spacing:1px;color:#888">This Week's Sales</h2>
    <table style="width:100%;border-collapse:collapse">${itemTable(itemResults)}</table>
  </div>
  ${commentary ? `
  <div style="background:#1a1a1a;border-radius:8px;padding:24px;margin-bottom:24px">
    <h2 style="margin:0 0 16px;font-size:16px;text-transform:uppercase;letter-spacing:1px;color:#aaa">Market Take</h2>
    <div style="color:#e8e4dc">${commentary.split(/\n\n+/).map(p => `<p style="line-height:1.7;font-size:15px">${esc(p)}</p>`).join('')}</div>
  </div>` : ''}
</div>
</body></html>`;
}

function renderMarketPage(niche, itemResults, commentary, weekOf) {
  const wLabel = label(weekOf);
  const origin = process.env.CLIENT_ORIGIN || 'https://www.collectrbrief.com';
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(niche.name)} Market Report — Week of ${wLabel} | CollectrBrief</title>
<meta name="description" content="${esc(niche.name)} price trends for the week of ${wLabel}: real sold prices from eBay and auction houses with AI market analysis. Updated every Sunday.">
<link rel="canonical" href="https://collectrbrief-api.onrender.com/market/${niche.slug}"></head>
<body style="margin:0;padding:0;background:#f9f6f1;font-family:Georgia,serif">
<div style="max-width:680px;margin:0 auto;padding:32px 16px">
  <div style="margin-bottom:24px">
    <a href="${origin}" style="font-size:22px;font-weight:700;color:#1a1a1a;text-decoration:none">CollectrBrief</a>
    <h1 style="font-size:26px;color:#1a1a1a;margin:16px 0 4px">${esc(niche.name)} Market Report</h1>
    <p style="color:#888;font-size:14px;margin:0">Week of ${wLabel} · Real sold prices, updated every Sunday</p>
  </div>
  <div style="background:#fff;border-radius:8px;padding:24px;margin-bottom:24px;border:1px solid #eee">
    <table style="width:100%;border-collapse:collapse">${itemTable(itemResults)}</table>
  </div>
  ${commentary ? `
  <div style="background:#1a1a1a;border-radius:8px;padding:24px;margin-bottom:24px">
    <h2 style="margin:0 0 16px;font-size:15px;text-transform:uppercase;letter-spacing:1px;color:#aaa">This Week's Take</h2>
    <div style="color:#e8e4dc">${commentary.split(/\n\n+/).map(p => `<p style="line-height:1.7;font-size:15px">${esc(p)}</p>`).join('')}</div>
  </div>` : ''}
  <div style="background:#fff;border:1px solid #eee;border-radius:8px;padding:24px;text-align:center;margin-bottom:24px">
    <p style="font-size:16px;font-weight:700;color:#1a1a1a;margin:0 0 4px">Track YOUR collection instead</p>
    <p style="color:#666;font-size:14px;margin:0 0 14px">Get this exact report for your specific items, in your inbox every Sunday. 14 days free.</p>
    <a href="${origin}/subscribe" style="display:inline-block;background:#1a1a1a;color:#fff;font-weight:700;padding:12px 28px;border-radius:6px;text-decoration:none;font-size:15px">Start free trial →</a>
  </div>
</div>
</body></html>`;
}

function renderTrendingPage(rankedItems, weekOf) {
  const wLabel = label(weekOf);
  const origin = process.env.CLIENT_ORIGIN || 'https://www.collectrbrief.com';
  const trendIcon = { up: '📈', down: '📉', stable: '➡️' };

  const rows = rankedItems.map((item, i) => `
    <tr>
      <td style="padding:16px 0;border-bottom:1px solid #eee">
        <div style="display:flex;justify-content:space-between;align-items:flex-start;gap:12px">
          <div>
            <span style="color:#c9922a;font-weight:700;font-size:13px;margin-right:8px">#${i + 1}</span>
            <span style="font-size:12px;color:#999;text-transform:uppercase;letter-spacing:0.04em">${esc(item.nicheName)}</span>
            <h3 style="margin:4px 0 4px;font-size:17px;color:#1a1a1a">${trendIcon[item.trend.trend] || '➡️'} ${esc(item.label)}</h3>
            <p style="margin:0;color:#666;font-size:13px">
              ${item.trend.count} sales · avg <strong>$${item.trend.avg}</strong> · range $${item.trend.min}–$${item.trend.max}
            </p>
          </div>
          <div style="text-align:right;flex-shrink:0">
            <div style="font-size:18px;font-weight:700;color:${(item.trend.pctChange || 0) >= 0 ? '#16a34a' : '#dc2626'}">
              ${(item.trend.pctChange || 0) >= 0 ? '+' : ''}${item.trend.pctChange || 0}%
            </div>
          </div>
        </div>
      </td>
    </tr>`).join('');

  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Trending This Week — Biggest Collectibles Price Movers | CollectrBrief</title>
<meta name="description" content="The biggest sold-price movers this week across sports cards, Pokémon, comics, and coins — real eBay and auction house data, ranked by percentage change. Updated every Sunday.">
<link rel="canonical" href="${origin}/trending"></head>
<body style="margin:0;padding:0;background:#f9f6f1;font-family:Georgia,serif">
<div style="max-width:680px;margin:0 auto;padding:32px 16px">
  <div style="margin-bottom:24px">
    <a href="${origin}" style="font-size:22px;font-weight:700;color:#1a1a1a;text-decoration:none">CollectrBrief</a>
    <h1 style="font-size:26px;color:#1a1a1a;margin:16px 0 4px">🔥 Trending This Week</h1>
    <p style="color:#888;font-size:14px;margin:0">Week of ${wLabel} · Biggest movers across all niches, ranked by % change</p>
  </div>
  <div style="background:#fff;border-radius:8px;padding:8px 24px;margin-bottom:24px;border:1px solid #eee">
    <table style="width:100%;border-collapse:collapse">${rows || '<tr><td style="padding:24px 0;color:#999;text-align:center">No movers to report yet — check back Sunday.</td></tr>'}</table>
  </div>
  <div style="background:#fff;border:1px solid #eee;border-radius:8px;padding:24px;text-align:center;margin-bottom:24px">
    <p style="font-size:16px;font-weight:700;color:#1a1a1a;margin:0 0 4px">Track YOUR items, not the whole market</p>
    <p style="color:#666;font-size:14px;margin:0 0 14px">Get personalized weekly moves for your specific collection, in your inbox every Sunday. 14 days free.</p>
    <a href="${origin}/subscribe" style="display:inline-block;background:#1a1a1a;color:#fff;font-weight:700;padding:12px 28px;border-radius:6px;text-decoration:none;font-size:15px">Start free trial →</a>
  </div>
</div>
</body></html>`;
}

function esc(str) {
  return String(str || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
function label(dateStr) {
  return new Date(dateStr).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
}
